"""baseline — full current schema (all tables as of the first migration)

Built from the live models via metadata.create_all so the baseline can never
drift from the ORM and is idempotent on a database that already has the tables
(it simply creates whatever is missing). Future changes are normal autogenerated
migrations (op.add_column, etc.).

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-17
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from app.db.base import Base
    from app.db import models  # noqa: F401 — register all tables on the metadata

    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    from app.db.base import Base
    from app.db import models  # noqa: F401

    Base.metadata.drop_all(bind=op.get_bind())
